# Generated by Django 4.0.3 on 2022-04-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommapp', '0002_alter_signup_mobno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='mobno',
            field=models.CharField(default='', max_length=100),
        ),
    ]
